name: Flutter CI/CD

# Déclenche le pipeline lors d'un push sur la branche main ou d'une pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définit les jobs à exécuter
jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configuration de Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  # Utilise la version stable de Flutter

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: flutter test

      # Étape 5 : Build de l'application Android
      - name: Build Android APK
        run: flutter build apk --release

      # Étape 6 : Upload de l'APK sur GitHub Releases (optionnel)
      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk