name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows virtual machine

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  # Use the stable channel of Flutter

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run tests
      - name: Run tests
        run: flutter test

      # Step 5: Build the Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # Step 6: Upload the APK to GitHub Releases (optional)
      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v4  # Use the latest version
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Step 7: Display a message
      - name: Display message
        run: echo "CI/CD pipeline has run successfully!"
